version: 2.1
jobs:
  build:
#     docker:
#       - image: manjarolinux/build
#     resource_class: small
    
    
    machine:
          image: "ubuntu-2204:current"
    resource_class: medium
    steps:
      - run: |
          sed -i 's/#Color/Color/g' /etc/pacman.conf
          sed -i 's/HoldPkg/#HoldPkg/g' /etc/pacman.conf
          sed -i 's/IgnorePkg/#IgnorePkg/g' /etc/pacman.conf
          cat /etc/pacman.conf

      - run: |
          pacman -Syu --noconfirm --color always
          pacman -Sy --noconfirm --color always --needed base-devel curl wget coreutils xterm git sudo yay asp bat socat colorgcc procps-ng nano nano-syntax-highlighting micro tree aria2 openssh man-db axel ffmpeg yt-dlp
      
      - run: sudo -u builder yay -Sy --color always --noconfirm paru-bin

      - run: comand_to_fail
workflows:
  main:
    jobs:
      - build
